#!/bin/bash

# fuehrt ./partdiff-openmp mit 1-1024 Interlines aus (Nur 2er Potenzen).

OUTPUT=""

for INTERLINES in 1 2 4 8 16 32 64 128 256 512 1024
do
    OUTPUT="${OUTPUT}Interlines = $INTERLINES"
    OUTPUT="${OUTPUT}"$'\n\n'
    for i in 1
    do
        BEFEHL="../partdiff-openmp 12 2 $INTERLINES 2 2 8196"
        OUTPUT="${OUTPUT}⟫ $BEFEHL"
        OUTPUT="${OUTPUT}"$'\n'
        OUTPUT="${OUTPUT} $($BEFEHL)"
        OUTPUT=${OUTPUT%Matrix:*}
        OUTPUT="${OUTPUT}--------------------------------------------------------------------------------"
        OUTPUT="${OUTPUT}"$'\n\n'
    done
done

OUTPUT="${OUTPUT}################################################################################"
OUTPUT="${OUTPUT}"$'\n\n'

echo "${OUTPUT}"
