#!/bin/bash

# fuehrt ./partdiff-openmp mit 5-11 Threads aus.

OUTPUT=""

for THREADS in 5 6 7 8 9 10 11
do
    OUTPUT="${OUTPUT}Threads = $THREADS"
    OUTPUT="${OUTPUT}"$'\n\n'
    for i in 1
    do
        BEFEHL="../partdiff-openmp $THREADS 2 512 2 2 10"
        OUTPUT="${OUTPUT}⟫ $BEFEHL"
        OUTPUT="${OUTPUT}"$'\n'
        OUTPUT="${OUTPUT} $($BEFEHL)"
        OUTPUT=${OUTPUT%Matrix:*}
        OUTPUT="${OUTPUT}--------------------------------------------------------------------------------"
        OUTPUT="${OUTPUT}"$'\n\n'
    done
done

OUTPUT="${OUTPUT}################################################################################"
OUTPUT="${OUTPUT}"$'\n\n'

echo "${OUTPUT}"
