#!/bin/bash

OUTPUT=''
for THREADS in 5 6 7 8 9 10 11
do
    OUTPUT="${OUTPUT}Threads = $THREADS"
    OUTPUT="${OUTPUT}"$'\n\n'
    OUTPUT="${OUTPUT}⟫ srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024"
    OUTPUT="${OUTPUT}"$'\n'
    OUTPUT="${OUTPUT} $( srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024)"
    OUTPUT=${OUTPUT%Matrix:*}
    OUTPUT="${OUTPUT}--------------------------------------------------------------------------------"
    OUTPUT="${OUTPUT}"$'\n\n'
    OUTPUT="${OUTPUT}⟫ srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024"
    OUTPUT="${OUTPUT}"$'\n'
    OUTPUT="${OUTPUT}$( srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024)"
    OUTPUT=${OUTPUT%Matrix:*}
    OUTPUT="${OUTPUT}--------------------------------------------------------------------------------"
    OUTPUT="${OUTPUT}"$'\n\n'
    OUTPUT="${OUTPUT}⟫ srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024"
    OUTPUT="${OUTPUT}"$'\n'
    OUTPUT="${OUTPUT}$( srun --jobid=96927 ./partdiff-openmp $THREADS 2 512 2 2 1024)"
    OUTPUT=${OUTPUT%Matrix:*}
    OUTPUT="${OUTPUT}"$'\n'
    OUTPUT="${OUTPUT}################################################################################"
    OUTPUT="${OUTPUT}"$'\n\n'
done

echo "${OUTPUT}" > job_script.out
