#!/bin/bash

OUTPUT=''
JOBID="96927"

for THREADS in 5 6 7 8 9 10 11
do
    echo "Iteration: $THREADS"
    OUTPUT="${OUTPUT}Threads = $THREADS"
    OUTPUT="${OUTPUT}"$'\n\n'
    for i in 1 2 3
    do
        BEFEHL="srun --jobid=$JOBID ./partdiff-openmp $THREADS 2 512 2 2 1024"
        OUTPUT="${OUTPUT}⟫ $BEFEHL"
        OUTPUT="${OUTPUT}"$'\n'
        OUTPUT="${OUTPUT} $($BEFEHL)"
        OUTPUT=${OUTPUT%Matrix:*}
        OUTPUT="${OUTPUT}--------------------------------------------------------------------------------"
        OUTPUT="${OUTPUT}"$'\n\n'
    done
    OUTPUT="${OUTPUT}################################################################################"
    OUTPUT="${OUTPUT}"$'\n\n'
done

echo "${OUTPUT}" > job_script.out
