# Common definitions
CC = gcc

# Compiler flags, paths and libraries
CFLAGS = -std=c99 -pedantic -Wall -Wextra -O2 -ggdb -fopenmp
LFLAGS = $(CFLAGS)
LIBS   = -lm

OBJSSEQ = partdiff-seq.o askparams.o
OBJSOPENMP = partdiff-openmp.o askparams.o

# Rule to create *.o from *.c
.c.o:
	$(CC) -c $(CFLAGS) $*.c

# Targets ...
all: partdiff-seq partdiff-openmp

partdiff-seq: $(OBJSSEQ) Makefile
	$(CC) $(LFLAGS) -o $@ $(OBJSSEQ) $(LIBS)
	
partdiff-openmp: $(OBJSOPENMP) Makefile
	$(CC) $(LFLAGS) -o $@ $(OBJSOPENMP) $(LIBS)

clean:
	$(RM) *.o *~

partdiff-seq.o: partdiff-seq.c Makefile

partdiff-openmp.o: partdiff-openmp.c Makefile

askparams.o: askparams.c Makefile
